[2024-12-15T19:02:24.502+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-12-15T19:02:24.531+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2024-12-15T19:02:24.541+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T19:02:24.561+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-12-15T19:02:24.562+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-12-15T19:02:24.563+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-15T19:02:24.575+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-15T19:02:24.576+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-12-15T19:02:24.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]>
[2024-12-15T19:02:24.584+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-12-15T19:02:24.585+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-15T19:02:24.592+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-12-15T19:02:24.593+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-15T19:02:24.594+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-12-15T19:02:24.594+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [queued]>
[2024-12-15T19:02:24.595+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-15T19:02:24.621+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_usernames> on 2024-12-15 18:57:13.338870+00:00
[2024-12-15T19:02:24.636+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=464) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T19:02:24.640+0000] {standard_task_runner.py:72} INFO - Started process 466 to run task
[2024-12-15T19:02:24.636+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiktok_dag', 'load_usernames', 'manual__2024-12-15T18:57:13.338870+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/tiktok_dag.py', '--cfg-path', '/tmp/tmp3_5u2uam']
[2024-12-15T19:02:24.642+0000] {standard_task_runner.py:105} INFO - Job 40: Subtask load_usernames
[2024-12-15T19:02:24.643+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7f2535759da0>]
[2024-12-15T19:02:24.720+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:57:13.338870+00:00 [running]> on host 589f938b62e1
[2024-12-15T19:02:24.781+0000] {taskinstance.py:2384} DEBUG - Clearing XCom data
[2024-12-15T19:02:24.803+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-12-15T19:02:24.847+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-12-15T19:02:24.863+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_dag' AIRFLOW_CTX_TASK_ID='load_usernames' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T18:57:13.338870+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T18:57:13.338870+00:00'
[2024-12-15T19:02:24.864+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-12-15T19:02:24.866+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-12-15T19:02:24.867+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T19:02:24.895+0000] {tiktok_dag.py:46} ERROR - Error while loading usernames: [Errno 2] No such file or directory: '/influencers.csv'
[2024-12-15T19:02:24.896+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_dag.py", line 41, in load_usernames
    usernames = te.read_usernames_from_csv(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_etl.py", line 93, in read_usernames_from_csv
    with open(file_path, "r") as csvfile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/influencers.csv'
[2024-12-15T19:02:24.918+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tiktok_dag, task_id=load_usernames, run_id=manual__2024-12-15T18:57:13.338870+00:00, execution_date=20241215T185713, start_date=20241215T190224, end_date=20241215T190224
[2024-12-15T19:02:24.939+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T19:02:24.942+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2024-12-15T19:02:24.943+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 40 for task load_usernames ([Errno 2] No such file or directory: '/influencers.csv'; 466)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_dag.py", line 41, in load_usernames
    usernames = te.read_usernames_from_csv(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_etl.py", line 93, in read_usernames_from_csv
    with open(file_path, "r") as csvfile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/influencers.csv'
[2024-12-15T19:02:24.978+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T19:02:24.996+0000] {taskinstance.py:3859} DEBUG - Skip locked rows, rollback
[2024-12-15T19:02:24.998+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
