[2024-12-15T18:18:07.138+0000] {__init__.py:54} DEBUG - Loading core task runner: StandardTaskRunner
[2024-12-15T18:18:07.171+0000] {base_task_runner.py:73} DEBUG - Planning to run as the  user
[2024-12-15T18:18:07.184+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-15T18:18:07.207+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-12-15T18:18:07.208+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-15T18:18:07.220+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2024-12-15T18:18:07.221+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-15T18:18:07.222+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2024-12-15T18:18:07.223+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]>
[2024-12-15T18:18:07.224+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2024-12-15T18:18:07.225+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-15T18:18:07.240+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2024-12-15T18:18:07.241+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-15T18:18:07.248+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2024-12-15T18:18:07.249+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [queued]>
[2024-12-15T18:18:07.250+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-15T18:18:07.283+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_usernames> on 2024-12-15 18:12:59.306576+00:00
[2024-12-15T18:18:07.305+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-15T18:18:07.299+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tiktok_dag', 'load_usernames', 'manual__2024-12-15T18:12:59.306576+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/tiktok_dag.py', '--cfg-path', '/tmp/tmp50e84o9d']
[2024-12-15T18:18:07.317+0000] {standard_task_runner.py:72} INFO - Started process 1499 to run task
[2024-12-15T18:18:07.317+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask load_usernames
[2024-12-15T18:18:07.336+0000] {cli_action_loggers.py:79} DEBUG - Calling callbacks: [<function default_action_log at 0x7fb249395da0>]
[2024-12-15T18:18:07.657+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_dag.load_usernames manual__2024-12-15T18:12:59.306576+00:00 [running]> on host 3354e0ae590e
[2024-12-15T18:18:08.115+0000] {taskinstance.py:2384} DEBUG - Clearing XCom data
[2024-12-15T18:18:08.222+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2024-12-15T18:18:08.415+0000] {retries.py:95} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2024-12-15T18:18:08.460+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tiktok_dag' AIRFLOW_CTX_TASK_ID='load_usernames' AIRFLOW_CTX_EXECUTION_DATE='2024-12-15T18:12:59.306576+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-15T18:12:59.306576+00:00'
[2024-12-15T18:18:08.464+0000] {__init__.py:115} DEBUG - Preparing lineage inlets and outlets
[2024-12-15T18:18:08.471+0000] {__init__.py:154} DEBUG - inlets: [], outlets: []
[2024-12-15T18:18:08.473+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-15T18:18:08.549+0000] {tiktok_dag.py:46} ERROR - Error while loading usernames: [Errno 2] No such file or directory: '/home/***/***_docker/dags/input/influencers.csv'
[2024-12-15T18:18:08.551+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_dag.py", line 41, in load_usernames
    usernames = te.read_usernames_from_csv(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_etl.py", line 93, in read_usernames_from_csv
    with open(file_path, "r") as csvfile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/airflow_docker/dags/input/influencers.csv'
[2024-12-15T18:18:08.620+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=tiktok_dag, task_id=load_usernames, run_id=manual__2024-12-15T18:12:59.306576+00:00, execution_date=20241215T181259, start_date=20241215T181807, end_date=20241215T181808
[2024-12-15T18:18:08.684+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-15T18:18:08.685+0000] {cli_action_loggers.py:98} DEBUG - Calling callbacks: []
[2024-12-15T18:18:08.687+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task load_usernames ([Errno 2] No such file or directory: '/home/airflow/airflow_docker/dags/input/influencers.csv'; 1499)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_dag.py", line 41, in load_usernames
    usernames = te.read_usernames_from_csv(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tiktok_etl.py", line 93, in read_usernames_from_csv
    with open(file_path, "r") as csvfile:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/airflow_docker/dags/input/influencers.csv'
[2024-12-15T18:18:08.756+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-15T18:18:08.859+0000] {dagrun.py:968} DEBUG - number of tis tasks for <DagRun tiktok_dag @ 2024-12-15 18:12:59.306576+00:00: manual__2024-12-15T18:12:59.306576+00:00, state:running, queued_at: 2024-12-15 18:12:59.601878+00:00. externally triggered: True>: 2 task(s)
[2024-12-15T18:18:08.860+0000] {dagrun.py:989} DEBUG - number of scheduleable tasks for <DagRun tiktok_dag @ 2024-12-15 18:12:59.306576+00:00: manual__2024-12-15T18:12:59.306576+00:00, state:running, queued_at: 2024-12-15 18:12:59.601878+00:00. externally triggered: True>: 1 task(s)
[2024-12-15T18:18:08.864+0000] {taskinstance.py:2423} DEBUG - Setting task state for <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-15T18:12:59.306576+00:00 [None]> to upstream_failed
[2024-12-15T18:18:08.866+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-15T18:12:59.306576+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_usernames'}
[2024-12-15T18:18:08.867+0000] {taskinstance.py:2603} DEBUG - Dependencies not met for <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-15T18:12:59.306576+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=1, upstream_failed=0, removed=0, done=1, success_setup=0, skipped_setup=0), upstream_task_ids={'load_usernames'}
[2024-12-15T18:18:08.868+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-15T18:12:59.306576+00:00 [upstream_failed]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2024-12-15T18:18:08.869+0000] {taskinstance.py:2625} DEBUG - <TaskInstance: tiktok_dag.fetch_all_user_data manual__2024-12-15T18:12:59.306576+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2024-12-15T18:18:08.877+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-15T18:18:08.890+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
